openapi: 3.0.3
info:
  title: Watch-List API
  version: 1.0.0
  description: A simple Platform, Movie, review API that helps us learn Django Rest
    Framework
paths:
  /account/api/token/:
    post:
      operationId: account_api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /account/api/token/refresh/:
    post:
      operationId: account_api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /account/login/:
    post:
      operationId: account_login_create
      tags:
      - account
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /account/logout/:
    post:
      operationId: account_logout_create
      description: Handles the logout action.
      tags:
      - account
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /account/register/:
    post:
      operationId: account_register_create
      tags:
      - account
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /watch/{id}/:
    get:
      operationId: watch_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: watch_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: watch_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /watch/{id}/review-create/:
    post:
      operationId: watch_review_create_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Review'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
  /watch/{id}/reviews/:
    get:
      operationId: watch_reviews_list
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
          description: ''
  /watch/list/:
    get:
      operationId: watch_list_retrieve
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: watch_list_create
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /watch/list2/:
    get:
      operationId: watch_list2_list
      parameters:
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - watch
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedWatchListList'
          description: ''
  /watch/review/:
    get:
      operationId: watch_review_list
      tags:
      - watch
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
          description: ''
  /watch/review/{id}/:
    get:
      operationId: watch_review_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    put:
      operationId: watch_review_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Review'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    patch:
      operationId: watch_review_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedReview'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedReview'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedReview'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    delete:
      operationId: watch_review_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /watch/streamplatform/:
    get:
      operationId: watch_streamplatform_list
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StreamPlatform'
          description: ''
    post:
      operationId: watch_streamplatform_create
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
  /watch/streamplatform/{id}/:
    get:
      operationId: watch_streamplatform_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    put:
      operationId: watch_streamplatform_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    patch:
      operationId: watch_streamplatform_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    delete:
      operationId: watch_streamplatform_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - watch
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - password
      - token
      - username
    PaginatedWatchListList:
      type: object
      required:
      - results
      properties:
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cD00ODY%3D"
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
        results:
          type: array
          items:
            $ref: '#/components/schemas/WatchList'
    PatchedReview:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        review_user:
          type: string
          readOnly: true
        rating:
          type: integer
          maximum: 5
          minimum: 1
        description:
          type: string
          nullable: true
          maxLength: 200
        active:
          type: boolean
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
    PatchedStreamPlatform:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        watchlist_set:
          type: array
          items:
            $ref: '#/components/schemas/WatchList'
          readOnly: true
        name:
          type: string
          maxLength: 30
        about:
          type: string
          maxLength: 150
        website:
          type: string
          format: uri
          maxLength: 100
    Review:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        review_user:
          type: string
          readOnly: true
        rating:
          type: integer
          maximum: 5
          minimum: 1
        description:
          type: string
          nullable: true
          maxLength: 200
        active:
          type: boolean
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
      required:
      - created
      - id
      - rating
      - review_user
      - updated
    StreamPlatform:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        watchlist_set:
          type: array
          items:
            $ref: '#/components/schemas/WatchList'
          readOnly: true
        name:
          type: string
          maxLength: 30
        about:
          type: string
          maxLength: 150
        website:
          type: string
          format: uri
          maxLength: 100
      required:
      - about
      - id
      - name
      - watchlist_set
      - website
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    WatchList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        platform:
          type: string
        title:
          type: string
          maxLength: 50
        storyline:
          type: string
          maxLength: 200
        active:
          type: boolean
        avg_rating:
          type: number
          format: double
        number_rating:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        created:
          type: string
          format: date-time
          readOnly: true
      required:
      - created
      - id
      - platform
      - storyline
      - title
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
